### ISSUE TITLE
nconf.get is not documented

### ISSUE THREAD

**Issue by vp-hwood** [indexzero/nconf#138]
`get` is not documented in the API Documentation section of the README. Does it return a new copy of the result each time? Or are we dealing with application-wide singletons here? Or something else? It doesn't matter for primitives but it could be a source of trouble for arrays and objects.

**Comment by localnerve** [comment]
I would also like to know this answer.

**Comment by Oza94** [comment]
Hi all,

I'm not sure of my response, but all objects returned by `nconf.merge()` are passed through [`common.merge()`](https://github.com/indexzero/nconf/blob/master/lib/nconf/common.js#L104). This function uses a temporary `MemoryStore` object to merge the results and the `MemoryStore.merge()` seems to copy only native types (and uses recursion on objects).

**So** I would say that `nconf.get()` returns a copy of the configuration object, **however** since the internal API of nconf is pretty complex, I'm not 100% sure that this is true.

**Comment by indexzero** [comment]
Closing in favor of a larger tracking issue #160.
