### ISSUE TITLE
How to reload config file

### ISSUE THREAD

**Issue by nvcken** [indexzero/nconf#145]
Example code
```javascript
 nconf.argv()
    .env()
    .file('configdev', 'configdev.json')
```
After server start a month , I edit configdev.json then how can I make nconf reload configdev.json without restart server?

**Comment by debonair** [comment]
I am also curious about how to do this.

**Comment by nvcken** [comment]
I found out.
Call nconf.reload()

**Comment by debonair** [comment]
what if you want to change the value of a config at runtime. like set a value to false temporarily?

**Comment by nvcken** [comment]
Do you mean set value of key
Have you try set() like 
nconf.set('database:host', '127.0.0.1');

**Comment by avimar** [comment]
Just for accessibility: people sometimes do this with a sighup for others, also, #145 and #69 
So you'd put this in your node script:

```
process.on('SIGHUP', function() {
  console.log('Got SIGHUP signal.');
  nconf.reload();
});
```

Uhm, I don't see nconf.reload() in the docs, so you might need to specify the files, e.g. from the docs:

```
  // Replace the file store with new settings
  nconf.use('file', { file: 'path/to/a-new/config-file.json' });
```

and then you can call something like ```pkill -HUP node``` or ```kill -1 $PID```

Make sure to add code to reset your DB connection or anything else persistent that needs to reload based on the config...

**Comment by indexzero** [comment]
Great discussion!

**Comment by walterpinson** [comment]
I have a scenario where I am running multiple integration tests; each dependent on specific configuration hierarchy snapshot.  The flow is something like this:

1. config.spec.js
  1.  `nconf.arg().env().file();`
  2.  Test config.json values
  2.  `process.env.<key>= 'dummy override config file value';`
  4.  Test environment variable overrides
2. someConfigurableFeature.spec.js
  1.  `nconf.arg().env().file();`
  2.  I think I'm pulling a fresh configuration but I am not
  2.  Test a config dependent function FAILS due to presence of dummy override values

A reload() or a reset() function would be very useful here as I want to start over from a blank slate.  Is there an existing way to achieve my objective that I just didn't understand from the documentation?

**Comment by avimar** [comment]
@walterpinson did you try `nconf.reload();` ?

Weird, since I can't even _find_ it in the code.

Alternatively, if you're changing many thing, you could/should just kill it `nconf=null` and re-`require` it.

**Comment by walterpinson** [comment]
My apologies.  It turns out that my issue had everything with the environment and nothing to do with nconf.

**Comment by mrdanimal** [comment]
Is `nconf.reload()` still the suggested way to handle reloading? Because I get this error: **"TypeError: nconf.reload is not a function"**
