### ISSUE TITLE
Found bug/limitation in naming

### ISSUE THREAD

**Issue by ArturPrzybysz** [indexzero/nconf#276]
I found that I cannot use ':' sign in variables name in *.json, e.g. nconf.get('scope:variable') returns undefined, while nconf.get('scope variable') works properly.

**Comment by mhamann** [comment]
@ArturPrzybysz nconf uses `:` as a hierarchy separator by default. How would it know whether `scope:variable` was an entire key vs. an object like `{ scope: { variable: <some value> } }`?

This is working as designed. If you have some thoughts about how your use case might work, feel free to share. Otherwise, I suggest we close this.
