### ISSUE TITLE
existsSync is not a function

### ISSUE THREAD

**Issue by hemikak** [indexzero/nconf#284]
Hi All,

I am getting 'existsSync undefined' when trying to load a file. Here is the stacktrace:

```
file.js:142 Uncaught TypeError: existsSync is not a function
    at ./node_modules/nconf/lib/nconf/stores/file.js.exports.File../node_modules/nconf/lib/nconf/stores/file.js.File.loadSync (file.js:142)
    at ./node_modules/nconf/lib/nconf/provider.js.exports.Provider../node_modules/nconf/lib/nconf/provider.js.Provider.add (provider.js:137)
    at ./node_modules/nconf/lib/nconf/provider.js.exports.Provider../node_modules/nconf/lib/nconf/provider.js.Provider.file (provider.js:63)
    at Object../src/index.js (index.js:15)
    at __webpack_require__ (bootstrap 1a62ac5286562409ee31:669)
    at fn (bootstrap 1a62ac5286562409ee31:87)
    at Object.0 (registerServiceWorker.js:108)
    at __webpack_require__ (bootstrap 1a62ac5286562409ee31:669)
    at bootstrap 1a62ac5286562409ee31:715
    at bundle.js:719
```
Heres my index.js.
```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/css/bootstrap-theme.css';
import nconf from 'nconf';

if (process.env.CONFIG_TYPE) {
    nconf.file(`../configs/${process.env.CONFIG_TYPE}.json`);
} else if (process.env.CONFIG_PATH) {
    nconf.file(process.env.CONFIG_PATH);
} else {
    nconf.argv().env().file({file:'/configs/dev.json'});
}

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();

```

Any thoughts on why I am getting this error ?
I created my project using 'npm install -g create-react-app'
Other info: 
npm -v  = 5.5.1
node -v = v8.8.1

Regards

**Comment by mhamann** [comment]
Given that you use React, I assume you're using webpack to create your application bundle? Can you post your webpack config?

**Comment by hemikak** [comment]
Hi @mhamann ,

I do not have a webpack config file. Using "create-react-app" does not create a webpack config. Here is my package.json.

```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "axios": "^0.17.0",
    "bootstrap": "^3.3.7",
    "prop-types": "^15.6.0",
    "nconf": "^0.8.5",
    "react": "^16.0.0",
    "react-bootstrap": "^0.31.5",
    "react-dom": "^16.0.0",
    "react-scripts": "1.0.14"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by mhamann** [comment]
Ok, so if you look at the webpack config that comes with create-react-app, you'll see that it has something like this included:

```
{
  node: {
    fs: 'empty'
  }
}
```

Since the `fs` module doesn't really do you any good in a browser, that config basically shims `fs` to return an empty object if ever it is required. That prevents compile errors; however, if a module actually tries to *use* `fs`, then it will throw runtime errors as you have pasted above.

The following StackOverflow question seems to provide some additional workarounds: https://stackoverflow.com/questions/40897832/node-cannot-find-module-fs-when-using-webpack

Be forewarned though, I do not think your use of nconf will ultimately work in the context of a browser, since it will not have access to your filesystem, because you are resolving configuration at *run time*.

I imagine you may want to resolve the configuration at *compile time* instead, in which it probably makes better sense to alias a single module name to whichever config you want to load (and then just pass it into nconf as an object). Unfortunately, that almost ensures that you'll need to eject from the create-react-app "magic" because you'll need to edit your webpack config. There are some ways to edit it without ejecting, but you'll have to research that on your own. :-)

In any case, if you do so, you could add some conditional logic like this to define a `config` module that simply references the appropriate json in your source tree:

```
if (process.env.CONFIG_FILE) {
    try {
        fs.accessSync(`./config/${process.env.CONFIG_FILE}`);
        config.resolve.alias.config = path.join(__dirname, 'config', process.env.CONFIG_FILE);
    } catch (e) {
        config.resolve.alias.config = path.join(__dirname, 'config', 'dev');
    }
} else {
    config.resolve.alias.config = path.join(__dirname, 'config', 'dev');
}
```

**Comment by hemikak** [comment]
Thanks! That helped!
