### ISSUE TITLE
nconf multi instance?

### ISSUE THREAD

**Issue by hugorodrigues** [indexzero/nconf#39]
Hi,

can i have multiple instances of nconf?

Something like:

``` javascript
var store1 = require('nconf').file({ file: __dirname+'/store1.json'});
var store2 = require('nconf').file({ file: __dirname+'/store2.json'});

store1.set('hello','store1');
store1.save();

store2.set('hello','store2');
store2.save();
```

This will only save "store2.json" file.

My goal is to read and **save** in multiple and independent files.
Any suggestion?

Thanks

**Comment by FelikZ** [comment]
It should be better documented about this feature. I spent around 1h to find this ticket.
Thanks.

**Comment by Deliaz** [comment]
@jfhbrook thanx!

**Comment by cameronwp** [comment]
+1 for better documentation. This was super useful but hard to find.

**Comment by jimlindeman** [comment]
Yes, this really should be emphasized to be used as best practice in the docs.  Reason to always use this is that otherwise, a base app's usage of nconf.use, nconf.file, and nconf.env may conflict with other npm libraries usage of the same nconf methods like in 'fabric-ca-client' library at: https://github.com/hyperledger/fabric-sdk-node/blob/v1.4.20/fabric-client/lib/Config.js
